# -*- coding: utf-8 -*-
"""Minibus_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SpMbMWks9Vtkmrvtq86YJ9CIKyKA4Xsv
"""

#Minibus_project
class Vehicle():
  def __init__(self,brand):
    self.brand=brand
  def start(self):
    print("vehicle satrted")
  def stop(self):
    print("vehicle stopped")
  def fuel(self):
    print("fuel has full")
class Car(Vehicle):
  def __init__(self,brand,seats,color,speed,model):
    super().__init__(brand)
    self.seats=seats
    self.color=color
    self.speed=speed
    self.model=model
  def shows(self):
    print("Brand:", self.brand)
    print("Seats:", self.seats)
    print("Color:", self.color)
    print("Speed:", self.speed)
    print("Model:", self.model)
c=Car("volvo",40,"Red",180,2019)
c2=Car("Toyota",40,"Blue",180,2020)
c.start()
c.fuel()
c.stop()

c2.shows()